# Generated by Django 2.1.7 on 2019-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
