# Generated by Django 2.1.7 on 2019-03-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activeuser_loggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='activeUser',
        ),
    ]
