# Generated by Django 2.1.7 on 2019-03-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('articles', '0016_auto_20190326_0347'),
        # ('admin', '0007_auto_20190326_0347'),
        ('users', '0006_auto_20190326_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
