# Generated by Django 2.1.7 on 2019-03-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190326_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
