# Generated by Django 2.1.7 on 2019-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_unregistereduser_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregistereduser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
