# Generated by Django 2.1.7 on 2019-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Basic', max_length=90),
            preserve_default=False,
        ),
    ]
