# Generated by Django 2.1.7 on 2019-03-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
