# Generated by Django 2.1.7 on 2019-03-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
