# Generated by Django 2.1.7 on 2019-03-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190326_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Querie',
        ),
    ]
